// Generated by CoffeeScript 1.10.0
(function() {
  var a, i, len, miVariable, name, ref, square, sum, times,
    slice = [].slice;

  miVariable = "hola";

  square = function(x) {
    return x * x;
  };

  sum = function() {
    var nums, result;
    nums = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    result = 0;
    nums.forEach(function(n) {
      return result += n;
    });
    return result;
  };

  a = "Hello";

  times = function(a, b) {
    return a * b;
  };

  console.log(sum(2, 4, 5));

  ref = ["Roger", "Aldo", "Manuel"];
  for (i = 0, len = ref.length; i < len; i++) {
    name = ref[i];
    console.log(name);
  }

}).call(this);

//# sourceMappingURL=sesion1.js.map
